### ISSUE TITLE
It seems short messages are not decoded

### ISSUE THREAD

**Issue by gariac** [rsadsb/dump1090_rs#117]
I put this in the "discussion" section but on second thought maybe I should bring this up as an issue. The Rust version decodes less messages than the "normal" dump1090 (if such a thing exists). It documented this in my comparison write up:
[Comparing rust version of dump1090](https://inplanesight.org/dump1090_rust.html) The traditional dump1090 decodes shorter messages. 

Is anything useful not being decoded? 

I find the rust version gets more position data which is the objective after all.

**Comment by wcampbell0x2a** [comment]
I'm getting a code 403 on that link.

**Comment by gariac** [comment]
> I'm getting a code 403 on that link.

Well I copied a list of bad referrers for my website and github.com was on it. This is where uttering "Doh!" is appropriate.

Could you try again. I hope this isn't going to be a browser cache issue. 

I attached all the images from the page.

![vrs3](https://github.com/rsadsb/dump1090_rs/assets/3691644/e775fc8d-7fce-417b-8a08-a743a8fd1be7)
![vrs2](https://github.com/rsadsb/dump1090_rs/assets/3691644/8ded5bf8-d8ca-454c-bf1d-e8aaba9467ca)
![messages](https://github.com/rsadsb/dump1090_rs/assets/3691644/2a01722b-8c59-40ca-9c25-1709e930e0cd)
![cpu](https://github.com/rsadsb/dump1090_rs/assets/3691644/9ec4936f-fc95-48bd-8c31-1f305e47c0f5)

**Comment by gariac** [comment]
> I'm getting a code 403 on that link.

The output from dump1090_rs are in the right hand panels.

**Comment by wcampbell0x2a** [comment]
Interesting! This rust version does decode short frames, you can read the number on the Stats display. Just, way way less. 

Interesting tool however, I'll have to play around with throughput and CPU usage.

**Comment by gariac** [comment]
> Interesting! This rust version does decode short frames, you can read the number on the Stats display. Just, way way less.
> 
> Interesting tool however, I'll have to play around with throughput and CPU usage.

Well two terminals side by side are just raw dumps. What could I have possibly done to build the code in a manner where it doesn't do short decodes? I will admit building Rust is quite foreign to me.

I just do a git clone and the link. Is there some secret sauce I need for git? 

The webpage link is fixed. (Actually nginx map fixed.) I did include the version of the program and cargo data.  I posted it below for convenience. 

`
The program is under development. This is a test of rev 0.7.

This is the installed version of cargo on Opensuse:
cargo -V
cargo 1.76.0

`

**Comment by wcampbell0x2a** [comment]
Pushed a WIP MR that _should_ fix this issue: https://github.com/rsadsb/dump1090_rs/pull/130

**Comment by gariac** [comment]
I'm not a programmer. Was I supposed to do something special or just  build the code. I'm still not seeing any short messages. I haven't  run VRS to collect stats but it is pretty obvious all the messages are the same length.

**Comment by wcampbell0x2a** [comment]
Just build the code from that branch, you should get SHORT and LONG messages in the output.

Here is an already built version: https://wcampbell.dev/public/bins/dump1090_rs

**Comment by gariac** [comment]
Your binary works. However I would like to know how to compile the code.

**Comment by wcampbell0x2a** [comment]
1. Install [rust](https://www.rust-lang.org/tools/install)
2. Install soapysdr-dev, for example on ubuntu: `apt install libsoapysdr-dev`
3. after cloning this repo, `cargo build --release`

**Comment by wcampbell0x2a** [comment]
Released fix in https://github.com/rsadsb/dump1090_rs/releases/tag/v0.8.0
