### ISSUE TITLE
Selecting antenna to use

### ISSUE THREAD

**Issue by bluecmd** [rsadsb/dump1090_rs#23]
Hi,

Thanks for the project! I am using dump1090_rs with my USRP B210 which has two antennas per frontend. Right now it does not appear to be possible to select which antenna to use, which is a bit annoying for my use case.

It appears it might be settable using [soapysdr::Device::set_antenna](https://kevinmehall.net/rustdoc/soapysdr/soapysdr/struct.Device.html#method.set_antenna).

Would you consider adding support for setting the antenna via e.g. command line options?

**Comment by wcampbell0x2a** [comment]
:wave: 

I always like hearing use cases, I added some code to support this via: https://github.com/rsadsb/dump1090_rs/commit/8aabe23e83d0e31ee5fb998df5e8921fc2e6d591.

I have some default setting that definitely aren't correct (gain wise). But I now let you change the `channel` and `antenna` via the config file using the `--custom-config` setting. I wasn't sure if you need to set the `channel`, but the antenna `name` should give you what you need.

If you find this works and have a working config, I would love to add it as a default `uhd` option. Let me know how this goes.

**Comment by wcampbell0x2a** [comment]
Added with https://github.com/rsadsb/dump1090_rs/pull/25
